### ISSUE TITLE
Modeling Questions

### ISSUE THREAD

**Issue by JacobGo** [CS326-Team-E/knapsack#1]
I think we should reconsider our Question model. Currently it has a single member value for answer, but this couples question and answer too closely. I suggest we create an Answer model with a corresponding question ID to join the two. This would allow multiple answers to a question as well as User as author and maybe even votes.

**Comment by GitHubdeWill** [comment]
Yes. I think that is a good idea

**Comment by JacobGo** [comment]
Not using Question model.
